spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: smovies
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 1800000